## Importando bibliotecas

In [1]:
import numpy as np
import pandas as pd

## Gerar dados

In [9]:
idade = np.array([10,10,10,10,30,30,30,30,30,30,30,30,50,50,50,50,70,70,70,90])
idade

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

## Tipo de classe

In [4]:
idade.dtype

dtype('int32')

In [5]:
# Ou
idade_rep = np.concatenate([np.repeat(10,4), np.repeat(30,8), np.repeat(50,4),np.repeat(70,3), np.repeat(90,1)])
idade_rep

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

In [7]:
# Ou
idade_rep = np.repeat(np.array([10,30,50,70,90]), repeats = [4,8,4,3,1], axis = 0)
idade_rep

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

## Verificando

In [10]:
idade==idade_rep

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

## Transformar em tabela (Data Frame)

In [13]:
table = pd.DataFrame(idade, columns=['a'])
table
#table.value_counts()
#table.columns = ['Idade', 'Freq']

a
0   10
1   10
2   10
3   10
4   30
5   30
6   30
7   30
8   30
9   30
10  30
11  30
12  50
13  50
14  50
15  50
16  70
17  70
18  70
19  90

## Calculando as frequências simples

In [14]:
table.groupby(['a']).size()

a
10    4
30    8
50    4
70    3
90    1
dtype: int64

## Quantidade total de alunos

In [16]:
table.groupby(['a']).size().sum()

20

In [17]:
tablenovo=pd.DataFrame(table.groupby(['a']).size())
tablenovo

0
a    
10  4
30  8
50  4
70  3
90  1

## Adicionar Colunas de Frequências

In [18]:
#table['Freq_acumulada'] = table['Freq'].cumsum()
tablenovo['Freq_acumulada'] = table.groupby(['a']).size().cumsum()
tablenovo

0  Freq_acumulada
a                    
10  4               4
30  8              12
50  4              16
70  3              19
90  1              20

In [20]:
tablenovo['Freq_relativa_simples'] = table.groupby(['a']).size().cumsum()/tablenovo['Freq_acumulada'].sum()
tablenovo

0  Freq_acumulada  Freq_relativa_simples
a                                           
10  4               4               0.056338
30  8              12               0.169014
50  4              16               0.225352
70  3              19               0.267606
90  1              20               0.281690

In [22]:
tablenovo['Freq_relativa_acumulada'] = tablenovo['Freq_relativa_simples'].cumsum()
tablenovo

0  Freq_acumulada  Freq_relativa_simples  Freq_relativa_acumulada
a                                                                    
10  4               4               0.056338                 0.056338
30  8              12               0.169014                 0.225352
50  4              16               0.225352                 0.450704
70  3              19               0.267606                 0.718310
90  1              20               0.281690                 1.000000

In [23]:
print(tablenovo.head())

    0  Freq_acumulada  Freq_relativa_simples  Freq_relativa_acumulada
a                                                                    
10  4               4               0.056338                 0.056338
30  8              12               0.169014                 0.225352
50  4              16               0.225352                 0.450704
70  3              19               0.267606                 0.718310
90  1              20               0.281690                 1.000000
